### PR TITLE
Add MustStringSlice method

### PR DESCRIPTION
**Pull request by gtfierro**
Supports the YAML syntax:

```
key:
 - list item 1
 - list item 2
```

I need it so I wrote it

### CODE REVIEW

**Comment by immesys** [comment]
Typically a Must\* method should give an error if the key is missing or of invalid type. rather than returning nil or silently dropping data

**Comment by gtfierro** [comment]
I absolutely agree and would prefer this behavior. However, the library
does not obey these semantics, so I kept mine consistent with what is
already in there. I might do a PR later tonight that implements this
behaviour instead

**Comment by immesys** [comment]
The existing Must methods will print an error if a value is missing or of the incorrect type. This method will silently ignore values of the incorrect type with no printed warning. That is what I was referring to.

**Comment by gtfierro** [comment]
Oh ok, I thought you meant the panic() behavior. I can have them print am
error sure

**Comment by immesys** [comment]
I'll let jack merge this in though, as he is maintaining sp now.

**Comment by gtfierro** [comment]
This should be ready now; we can talk later about if we want the pattern where there are two methods:

```
GetString(key) (string, error)
MustGetString(key) string // panics
```

**Pull request merged**
